"""FastAPI REST API layer for the acquisition platform.

Exposes every optimization engine as a JSON endpoint:

- POST /match            — buyer-seller matching (GAP)
- POST /value            — business valuation (DCF, Comps, SDE, ARR, Ensemble)
- POST /fraud-check      — fraud detection (signals + graph analysis)
- POST /optimize         — portfolio optimization (MIQP)
- POST /price            — dynamic pricing (Stackelberg-inspired)
- POST /resolve          — entity resolution (blocking + Jaro-Winkler)
- POST /rank             — search ranking (submodular maximization)
- POST /evolve           — evolution optimization (genetic algorithm)
- POST /auction          — auction design (Vickrey, GSP, English, Dutch)
- POST /due-diligence    — due diligence scheduling
- POST /cross-border     — cross-border deal optimization
- POST /recommend        — hybrid recommendations
- POST /pipeline         — full orchestration pipeline
- GET  /health           — health check
- GET  /metrics          — platform metrics

All request/response bodies are validated with Pydantic models. The
OpenAPI schema is auto-generated by FastAPI and served at /openapi.json
with interactive docs at /docs.
"""

from __future__ import annotations

import time
from enum import Enum
from typing import Any, Callable, Optional

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field, field_validator

from acquisition_platform.exceptions import (
    AcquisitionPlatformError,
    DivisionByZeroError,
    EmptyInputError,
    InvalidRangeError,
    ValidationError,
)
from acquisition_platform.matching import Buyer, BuyerSellerMatcher, Seller
from acquisition_platform.valuation import ValuationEngine
from acquisition_platform.fraud_detection import FraudDetector, FraudSignal
from acquisition_platform.portfolio_optimizer import Asset, PortfolioOptimizer
from acquisition_platform.dynamic_pricing import PricingEngine
from acquisition_platform.entity_resolution import EntityResolver
from acquisition_platform.search_ranking import Listing, SearchRanker
from acquisition_platform.evolution import EvolutionEngine
from acquisition_platform.auction_design import AuctionConfig, AuctionDesigner, Bid
from acquisition_platform.due_diligence import (
    DueDiligenceScheduler,
    DueDiligenceTask,
    Reviewer,
)
from acquisition_platform.cross_border import (
    CrossBorderAnalyzer,
    CrossBorderDeal,
)
from acquisition_platform.recommendation import (
    ItemProfile,
    RecommendationEngine,
    UserProfile,
)
from acquisition_platform.orchestrator import AcquisitionPipeline, PipelineConfig

# ---------------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Acquisition Platform API",
    description=(
        "REST API for the acquisition platform research & optimization engine. "
        "Solves NP-hard problems: matching, valuation, fraud detection, "
        "portfolio optimization, dynamic pricing, entity resolution, "
        "search ranking, and due diligence scheduling."
    ),
    version="0.1.0",
)

_START_TIME = time.monotonic()

# In-memory metrics counters
_METRICS: dict[str, Any] = {
    "total_requests": 0,
    "total_errors": 0,
    "endpoints": {},
}


def _record_request(path: str, status_code: int) -> None:
    """Record a request in the metrics counters."""
    _METRICS["total_requests"] += 1
    ep = _METRICS["endpoints"].setdefault(
        path, {"requests": 0, "errors": 0}
    )
    ep["requests"] += 1
    if status_code >= 400:
        _METRICS["total_errors"] += 1
        ep["errors"] += 1


@app.middleware("http")
async def metrics_middleware(request: Request, call_next: Callable[..., Any]) -> Any:
    """Track request counts and error rates per endpoint."""
    response = await call_next(request)
    _record_request(request.url.path, response.status_code)
    return response


# ---------------------------------------------------------------------------
# Exception handlers
# ---------------------------------------------------------------------------


def _error_response(exc: AcquisitionPlatformError, status_code: int) -> JSONResponse:
    """Build a consistent JSON error response."""
    return JSONResponse(
        status_code=status_code,
        content={"detail": str(exc), "error_type": type(exc).__name__},
    )


@app.exception_handler(EmptyInputError)
async def empty_input_handler(request: Request, exc: EmptyInputError) -> JSONResponse:
    return _error_response(exc, 422)


@app.exception_handler(ValidationError)
async def validation_error_handler(request: Request, exc: ValidationError) -> JSONResponse:
    return _error_response(exc, 422)


@app.exception_handler(InvalidRangeError)
async def invalid_range_handler(request: Request, exc: InvalidRangeError) -> JSONResponse:
    return _error_response(exc, 422)


@app.exception_handler(DivisionByZeroError)
async def division_by_zero_handler(request: Request, exc: DivisionByZeroError) -> JSONResponse:
    return _error_response(exc, 422)


@app.exception_handler(AcquisitionPlatformError)
async def platform_error_handler(request: Request, exc: AcquisitionPlatformError) -> JSONResponse:
    return _error_response(exc, 500)


# ---------------------------------------------------------------------------
# Pydantic models — request/response validation
# ---------------------------------------------------------------------------


class BuyerRequest(BaseModel):
    id: str
    budget: float = Field(gt=0)
    preferences: dict[str, Any] = Field(default_factory=dict)


class SellerRequest(BaseModel):
    id: str
    asking_price: float = Field(gt=0)
    attributes: dict[str, Any] = Field(default_factory=dict)


class MatchRequest(BaseModel):
    buyers: list[BuyerRequest] = Field(min_length=1)
    sellers: list[SellerRequest] = Field(min_length=1)


class MatchResponse(BaseModel):
    buyer_id: str
    seller_id: str
    score: float
    confidence: float


class MatchResult(BaseModel):
    matches: list[MatchResponse]
    count: int


class ValuationMethod(str, Enum):
    DCF = "dcf"
    COMPS = "comps"
    SDE = "sde"
    ARR = "arr"
    ENSEMBLE = "ensemble"


class ValuationRequest(BaseModel):
    method: ValuationMethod
    free_cash_flow: Optional[float] = Field(default=None, ge=0)
    growth_rate: Optional[float] = Field(default=None, ge=0)
    discount_rate: Optional[float] = Field(default=None, ge=0)
    terminal_growth: Optional[float] = Field(default=None, ge=0)
    years: Optional[int] = Field(default=None, gt=0)
    metric: Optional[float] = Field(default=None, ge=0)
    multiple: Optional[float] = Field(default=None, ge=0)
    revenue: Optional[float] = Field(default=None, ge=0)
    revenue_multiple: Optional[float] = Field(default=None, ge=0)
    sde: Optional[float] = Field(default=None, ge=0)
    arr: Optional[float] = Field(default=None, ge=0)


class ValuationResponse(BaseModel):
    value: float
    method: str
    confidence: float
    low_estimate: float
    high_estimate: float


class FraudSignalRequest(BaseModel):
    name: str
    value: float = Field(ge=0.0, le=1.0)


class FraudGraphRequest(BaseModel):
    nodes: list[str]
    edges: list[tuple[str, str]]


class FraudCheckRequest(BaseModel):
    signals: Optional[list[FraudSignalRequest]] = None
    graph: Optional[FraudGraphRequest] = None


class FraudCheckResponse(BaseModel):
    score: float
    risk_level: str
    confidence: float
    explanations: list[str]
    has_ring: Optional[bool] = None
    risk_score: Optional[float] = None


class AssetRequest(BaseModel):
    id: str
    cost: float = Field(ge=0)
    expected_return: float
    risk: float = Field(ge=0)
    sector: str = ""


class OptimizeRequest(BaseModel):
    budget: float = Field(gt=0)
    max_assets: int = Field(default=10, gt=0)
    risk_tolerance: float = Field(ge=0.0, le=1.0)
    assets: list[AssetRequest] = Field(min_length=1)


class AssetResponse(BaseModel):
    id: str
    cost: float
    expected_return: float
    risk: float
    sector: str


class OptimizeResponse(BaseModel):
    assets: list[AssetResponse]
    expected_return: float
    sharpe_ratio: float


class PriceRequest(BaseModel):
    base_value: float = Field(gt=0)
    demand_level: float = Field(ge=0.0, le=1.0)
    competition_level: float = Field(ge=0.0, le=1.0)
    market_condition: str

    @field_validator("market_condition")
    @classmethod
    def _valid_condition(cls, v: str) -> str:
        if v not in {"bull", "bear", "normal"}:
            raise ValueError("market_condition must be one of: bull, bear, normal")
        return v


class PriceResponse(BaseModel):
    recommended_price: float
    confidence: float
    floor_price: float
    ceiling_price: float
    equilibrium_price: float


class EntityRequest(BaseModel):
    name: str
    domain: Optional[str] = None
    id: Optional[str] = None


class ResolveRequest(BaseModel):
    entities: list[EntityRequest] = Field(min_length=1)
    threshold: float = Field(default=0.85, ge=0.0, le=1.0)


class EntityClusterResponse(BaseModel):
    entities: list[dict[str, Any]]
    canonical_name: str


class ResolveResponse(BaseModel):
    clusters: list[EntityClusterResponse]
    count: int


class ListingRequest(BaseModel):
    id: str
    title: str
    relevance: float = Field(ge=0.0, le=1.0)
    category: str = ""


class RankRequest(BaseModel):
    query: str
    listings: list[ListingRequest] = Field(min_length=1)
    user_preferences: Optional[dict[str, Any]] = None


class RankedListingResponse(BaseModel):
    id: str
    title: str
    score: float
    category: str


class RankResponse(BaseModel):
    rankings: list[RankedListingResponse]
    count: int


class FitnessFunction(str, Enum):
    QUADRATIC = "quadratic"
    SINE = "sine"


class EvolveRequest(BaseModel):
    population_size: int = Field(default=50, gt=0)
    generations: int = Field(default=20, gt=0)
    mutation_rate: float = Field(default=0.1, ge=0.0, le=1.0)
    elitism: int = Field(default=2, ge=0)
    gene_min: float = 0.0
    gene_max: float = 1.0
    fitness: FitnessFunction = FitnessFunction.QUADRATIC

    @field_validator("gene_max")
    @classmethod
    def _valid_range(cls, v: float, info: Any) -> float:
        if "gene_min" in info.data and v <= info.data["gene_min"]:
            raise ValueError("gene_max must be greater than gene_min")
        return v


class EvolveResponse(BaseModel):
    best_fitness: float
    generation_count: int
    population_size: int
    diversity: float
    offspring_count: int
    converged: bool
    worst_fitness: float


class BidRequest(BaseModel):
    bidder_id: str
    amount: float


class AuctionConfigRequest(BaseModel):
    format: str
    reserve_price: float
    min_increment: float

    @field_validator("format")
    @classmethod
    def _valid_format(cls, v: str) -> str:
        if v not in {"vickrey", "gsp", "english", "dutch"}:
            raise ValueError("format must be one of: vickrey, gsp, english, dutch")
        return v


class AuctionRequest(BaseModel):
    bids: list[BidRequest]
    config: AuctionConfigRequest


class AuctionResponse(BaseModel):
    winner_id: Optional[str]
    winning_bid: float
    revenue: float
    format: str


class DueDiligenceTaskRequest(BaseModel):
    id: str
    name: str
    duration: float = Field(gt=0)
    expertise: str
    dependencies: list[str] = Field(default_factory=list)


class ReviewerRequest(BaseModel):
    id: str
    name: str
    expertise: list[str]
    availability: float = Field(gt=0)


class DueDiligenceRequest(BaseModel):
    tasks: list[DueDiligenceTaskRequest]
    reviewers: list[ReviewerRequest]


class DueDiligenceResponse(BaseModel):
    assignments: list[dict[str, Any]]
    makespan: float
    reviewer_utilization: dict[str, float]


class CrossBorderDealRequest(BaseModel):
    acquirer_country: str
    target_country: str
    deal_value: float = Field(ge=0)
    currency: str
    industry: str


class CrossBorderRequest(BaseModel):
    deal: CrossBorderDealRequest


class CrossBorderResponse(BaseModel):
    currency_risk: float
    regulatory_risk: float
    tax_optimization: float
    cultural_distance: float
    timeline_months: int


class UserProfileRequest(BaseModel):
    user_id: str
    preferences: dict[str, str] = Field(default_factory=dict)
    history: list[str] = Field(default_factory=list)


class ItemProfileRequest(BaseModel):
    item_id: str
    attributes: dict[str, str] = Field(default_factory=dict)
    category: str = ""


class RecommendRequest(BaseModel):
    user: UserProfileRequest
    items: list[ItemProfileRequest] = Field(min_length=1)
    k: int = Field(default=10, gt=0)


class RecommendationResponse(BaseModel):
    item_id: str
    score: float
    reason: str


class RecommendResponse(BaseModel):
    recommendations: list[RecommendationResponse]
    diversity_score: float
    coverage: float


class PipelineConfigRequest(BaseModel):
    enable_matching: bool = True
    enable_valuation: bool = True
    enable_fraud: bool = True
    enable_portfolio: bool = True
    enable_pricing: bool = True
    enable_ranking: bool = True
    enable_evolution: bool = True


class PipelineRequest(BaseModel):
    entities: list[dict[str, Any]]
    config: Optional[PipelineConfigRequest] = None


class PipelineResponse(BaseModel):
    matches: list[MatchResponse]
    valuations: list[ValuationResponse]
    fraud_scores: list[FraudCheckResponse]
    portfolio: Optional[OptimizeResponse]
    prices: list[PriceResponse]
    rankings: list[RankedListingResponse]
    evolution_result: Optional[EvolveResponse]


class HealthResponse(BaseModel):
    status: str
    version: str
    uptime_seconds: float


class MetricsResponse(BaseModel):
    total_requests: int
    total_errors: int
    uptime_seconds: float
    endpoints: dict[str, Any]


# ---------------------------------------------------------------------------
# System endpoints
# ---------------------------------------------------------------------------


@app.get("/health", response_model=HealthResponse, tags=["system"])
def health_check() -> HealthResponse:
    """Health check endpoint."""
    return HealthResponse(
        status="ok",
        version="0.1.0",
        uptime_seconds=round(time.monotonic() - _START_TIME, 3),
    )


@app.get("/metrics", response_model=MetricsResponse, tags=["system"])
def metrics() -> MetricsResponse:
    """Platform metrics: request counts, error rates, uptime."""
    return MetricsResponse(
        total_requests=_METRICS["total_requests"],
        total_errors=_METRICS["total_errors"],
        uptime_seconds=round(time.monotonic() - _START_TIME, 3),
        endpoints=dict(_METRICS["endpoints"]),
    )


# ---------------------------------------------------------------------------
# Engine endpoints
# ---------------------------------------------------------------------------


@app.post("/match", response_model=MatchResult, tags=["engines"])
def match(request: MatchRequest) -> MatchResult:
    """Match buyers to sellers using the GAP solver."""
    buyers = [Buyer(id=b.id, budget=b.budget, preferences=b.preferences) for b in request.buyers]
    sellers = [Seller(id=s.id, asking_price=s.asking_price, attributes=s.attributes) for s in request.sellers]
    matcher = BuyerSellerMatcher()
    matches = matcher.match(buyers, sellers)
    return MatchResult(
        matches=[
            MatchResponse(
                buyer_id=m.buyer_id,
                seller_id=m.seller_id,
                score=m.score,
                confidence=m.confidence,
            )
            for m in matches
        ],
        count=len(matches),
    )


@app.post("/value", response_model=ValuationResponse, tags=["engines"])
def value(request: ValuationRequest) -> ValuationResponse:
    """Compute business valuation using the specified method."""
    engine = ValuationEngine()
    method = request.method

    if method == ValuationMethod.DCF:
        if request.free_cash_flow is None or request.growth_rate is None or request.discount_rate is None or request.terminal_growth is None or request.years is None:
            raise ValidationError("DCF requires free_cash_flow, growth_rate, discount_rate, terminal_growth, years")
        if request.discount_rate == request.terminal_growth:
            raise DivisionByZeroError("discount_rate and terminal_growth cannot be equal")
        result = engine.dcf_valuation(
            free_cash_flow=request.free_cash_flow,
            growth_rate=request.growth_rate,
            discount_rate=request.discount_rate,
            terminal_growth=request.terminal_growth,
            years=request.years,
        )
    elif method == ValuationMethod.COMPS:
        if request.metric is None or request.multiple is None:
            raise ValidationError("Comps requires metric and multiple")
        result = engine.comparable_valuation(metric=request.metric, multiple=request.multiple)
    elif method == ValuationMethod.SDE:
        if request.sde is None or request.multiple is None:
            raise ValidationError("SDE requires sde and multiple")
        result = engine.sde_valuation(sde=request.sde, multiple=request.multiple)
    elif method == ValuationMethod.ARR:
        if request.arr is None or request.multiple is None:
            raise ValidationError("ARR requires arr and multiple")
        result = engine.arr_valuation(arr=request.arr, multiple=request.multiple)
    elif method == ValuationMethod.ENSEMBLE:
        if request.free_cash_flow is None or request.revenue is None or request.growth_rate is None or request.discount_rate is None or request.terminal_growth is None or request.revenue_multiple is None or request.years is None:
            raise ValidationError("Ensemble requires free_cash_flow, revenue, growth_rate, discount_rate, terminal_growth, revenue_multiple, years")
        result = engine.ensemble_valuation(
            free_cash_flow=request.free_cash_flow,
            revenue=request.revenue,
            growth_rate=request.growth_rate,
            discount_rate=request.discount_rate,
            terminal_growth=request.terminal_growth,
            revenue_multiple=request.revenue_multiple,
            years=request.years,
        )
    else:
        raise ValidationError(f"Unknown valuation method: {method}")

    return ValuationResponse(
        value=result.value,
        method=result.method,
        confidence=result.confidence,
        low_estimate=result.low_estimate,
        high_estimate=result.high_estimate,
    )


@app.post("/fraud-check", response_model=FraudCheckResponse, tags=["engines"])
def fraud_check(request: FraudCheckRequest) -> FraudCheckResponse:
    """Detect fraud via signal scoring or graph analysis."""
    detector = FraudDetector()

    if request.signals is not None:
        if len(request.signals) == 0:
            return FraudCheckResponse(
                score=0.0,
                risk_level="low",
                confidence=0.0,
                explanations=["No signals provided"],
            )
        signals = [FraudSignal(name=s.name, value=s.value) for s in request.signals]
        result = detector.score(signals)
        return FraudCheckResponse(
            score=result.score,
            risk_level=result.risk_level,
            confidence=result.confidence,
            explanations=result.explanations,
        )

    if request.graph is not None:
        graph = {"nodes": request.graph.nodes, "edges": request.graph.edges}
        result = detector.analyze_graph(graph)
        return FraudCheckResponse(
            score=result.score,
            risk_level=result.risk_level,
            confidence=result.confidence,
            explanations=result.explanations,
            has_ring=result.has_ring,
            risk_score=result.risk_score,
        )

    raise ValidationError("Either signals or graph must be provided")


@app.post("/optimize", response_model=OptimizeResponse, tags=["engines"])
def optimize(request: OptimizeRequest) -> OptimizeResponse:
    """Optimize portfolio using greedy MIQP approximation."""
    assets = [
        Asset(id=a.id, cost=a.cost, expected_return=a.expected_return, risk=a.risk, sector=a.sector)
        for a in request.assets
    ]
    optimizer = PortfolioOptimizer(budget=request.budget, max_assets=request.max_assets)
    portfolio = optimizer.optimize(assets, risk_tolerance=request.risk_tolerance)
    return OptimizeResponse(
        assets=[
            AssetResponse(
                id=a.id,
                cost=a.cost,
                expected_return=a.expected_return,
                risk=a.risk,
                sector=a.sector,
            )
            for a in portfolio.assets
        ],
        expected_return=portfolio.expected_return,
        sharpe_ratio=portfolio.sharpe_ratio,
    )


@app.post("/price", response_model=PriceResponse, tags=["engines"])
def price(request: PriceRequest) -> PriceResponse:
    """Compute dynamic price recommendation."""
    engine = PricingEngine()
    result = engine.recommend_price(
        base_value=request.base_value,
        demand_level=request.demand_level,
        competition_level=request.competition_level,
        market_condition=request.market_condition,
    )
    return PriceResponse(
        recommended_price=result.recommended_price,
        confidence=result.confidence,
        floor_price=result.floor_price,
        ceiling_price=result.ceiling_price,
        equilibrium_price=result.equilibrium_price,
    )


@app.post("/resolve", response_model=ResolveResponse, tags=["engines"])
def resolve(request: ResolveRequest) -> ResolveResponse:
    """Resolve entities into clusters using blocking + Jaro-Winkler."""
    entities = [e.model_dump(exclude_none=True) for e in request.entities]
    resolver = EntityResolver(threshold=request.threshold)
    clusters = resolver.resolve(entities)
    return ResolveResponse(
        clusters=[
            EntityClusterResponse(
                entities=[dict(e) for e in c.entities],
                canonical_name=c.canonical_name,
            )
            for c in clusters
        ],
        count=len(clusters),
    )


@app.post("/rank", response_model=RankResponse, tags=["engines"])
def rank(request: RankRequest) -> RankResponse:
    """Rank listings by relevance, diversity, and personalization."""
    listings = [
        Listing(id=l.id, title=l.title, relevance=l.relevance, category=l.category)
        for l in request.listings
    ]
    ranker = SearchRanker()
    results = ranker.rank(request.query, listings, user_preferences=request.user_preferences)
    return RankResponse(
        rankings=[
            RankedListingResponse(
                id=r.id,
                title=r.title,
                score=r.score,
                category=r.category,
            )
            for r in results
        ],
        count=len(results),
    )


@app.post("/evolve", response_model=EvolveResponse, tags=["engines"])
def evolve(request: EvolveRequest) -> EvolveResponse:
    """Run genetic algorithm evolution for hyperparameter optimization."""
    engine = EvolutionEngine(
        population_size=request.population_size,
        generations=request.generations,
        mutation_rate=request.mutation_rate,
        elitism=request.elitism,
    )

    if request.fitness == FitnessFunction.QUADRATIC:
        fitness_fn = lambda gene: -((gene - 0.5) ** 2) + 1.0
    else:
        import math
        fitness_fn = lambda gene: math.sin(gene * math.pi)

    result = engine.evolve(fitness_fn, (request.gene_min, request.gene_max))
    return EvolveResponse(
        best_fitness=result.best_fitness,
        generation_count=result.generation_count,
        population_size=result.population_size,
        diversity=result.diversity,
        offspring_count=result.offspring_count,
        converged=result.converged,
        worst_fitness=result.worst_fitness,
    )


@app.post("/auction", response_model=AuctionResponse, tags=["engines"])
def auction(request: AuctionRequest) -> AuctionResponse:
    """Run an auction with the given bids and configuration."""
    bids = [Bid(bidder_id=b.bidder_id, amount=b.amount) for b in request.bids]
    config = AuctionConfig(
        format=request.config.format,
        reserve_price=request.config.reserve_price,
        min_increment=request.config.min_increment,
    )
    designer = AuctionDesigner()
    result = designer.design_auction(bids, config)
    return AuctionResponse(
        winner_id=result.winner_id,
        winning_bid=result.winning_bid,
        revenue=result.revenue,
        format=result.format,
    )


@app.post("/due-diligence", response_model=DueDiligenceResponse, tags=["engines"])
def due_diligence(request: DueDiligenceRequest) -> DueDiligenceResponse:
    """Schedule due diligence tasks across reviewers."""
    tasks = [
        DueDiligenceTask(
            id=t.id,
            name=t.name,
            duration=t.duration,
            expertise=t.expertise,
            dependencies=t.dependencies,
        )
        for t in request.tasks
    ]
    reviewers = [
        Reviewer(id=r.id, name=r.name, expertise=r.expertise, availability=r.availability)
        for r in request.reviewers
    ]
    scheduler = DueDiligenceScheduler()
    result = scheduler.schedule(tasks, reviewers)
    return DueDiligenceResponse(
        assignments=result.assignments,
        makespan=result.makespan,
        reviewer_utilization=result.reviewer_utilization,
    )


@app.post("/cross-border", response_model=CrossBorderResponse, tags=["engines"])
def cross_border(request: CrossBorderRequest) -> CrossBorderResponse:
    """Analyze cross-border M&A transaction."""
    deal = CrossBorderDeal(
        acquirer_country=request.deal.acquirer_country,
        target_country=request.deal.target_country,
        deal_value=request.deal.deal_value,
        currency=request.deal.currency,
        industry=request.deal.industry,
    )
    analyzer = CrossBorderAnalyzer()
    result = analyzer.generate_cross_border_report(deal)
    return CrossBorderResponse(
        currency_risk=result.currency_risk,
        regulatory_risk=result.regulatory_risk,
        tax_optimization=result.tax_optimization,
        cultural_distance=result.cultural_distance,
        timeline_months=result.timeline_months,
    )


@app.post("/recommend", response_model=RecommendResponse, tags=["engines"])
def recommend(request: RecommendRequest) -> RecommendResponse:
    """Generate hybrid recommendations for a user."""
    user = UserProfile(
        user_id=request.user.user_id,
        preferences=request.user.preferences,
        history=request.user.history,
    )
    items = [
        ItemProfile(item_id=i.item_id, attributes=i.attributes, category=i.category)
        for i in request.items
    ]
    engine = RecommendationEngine()
    result = engine.recommend(user, items, k=request.k)
    return RecommendResponse(
        recommendations=[
            RecommendationResponse(
                item_id=r.item_id,
                score=r.score,
                reason=r.reason,
            )
            for r in result.recommendations
        ],
        diversity_score=result.diversity_score,
        coverage=result.coverage,
    )


@app.post("/pipeline", response_model=PipelineResponse, tags=["engines"])
def pipeline(request: PipelineRequest) -> PipelineResponse:
    """Run the full acquisition pipeline."""
    config = PipelineConfig()
    if request.config is not None:
        config = PipelineConfig(
            enable_matching=request.config.enable_matching,
            enable_valuation=request.config.enable_valuation,
            enable_fraud=request.config.enable_fraud,
            enable_portfolio=request.config.enable_portfolio,
            enable_pricing=request.config.enable_pricing,
            enable_ranking=request.config.enable_ranking,
            enable_evolution=request.config.enable_evolution,
        )
    orchestrator = AcquisitionPipeline()
    result = orchestrator.run(request.entities, config)

    portfolio_response = None
    if result.portfolio is not None:
        portfolio_response = OptimizeResponse(
            assets=[
                AssetResponse(
                    id=a.id,
                    cost=a.cost,
                    expected_return=a.expected_return,
                    risk=a.risk,
                    sector=a.sector,
                )
                for a in result.portfolio.assets
            ],
            expected_return=result.portfolio.expected_return,
            sharpe_ratio=result.portfolio.sharpe_ratio,
        )

    evolution_response = None
    if result.evolution_result is not None:
        evolution_response = EvolveResponse(
            best_fitness=result.evolution_result.best_fitness,
            generation_count=result.evolution_result.generation_count,
            population_size=result.evolution_result.population_size,
            diversity=result.evolution_result.diversity,
            offspring_count=result.evolution_result.offspring_count,
            converged=result.evolution_result.converged,
            worst_fitness=result.evolution_result.worst_fitness,
        )

    return PipelineResponse(
        matches=[
            MatchResponse(
                buyer_id=m.buyer_id,
                seller_id=m.seller_id,
                score=m.score,
                confidence=m.confidence,
            )
            for m in result.matches
        ],
        valuations=[
            ValuationResponse(
                value=v.value,
                method=v.method,
                confidence=v.confidence,
                low_estimate=v.low_estimate,
                high_estimate=v.high_estimate,
            )
            for v in result.valuations
        ],
        fraud_scores=[
            FraudCheckResponse(
                score=f.score,
                risk_level=f.risk_level,
                confidence=f.confidence,
                explanations=f.explanations,
            )
            for f in result.fraud_scores
        ],
        portfolio=portfolio_response,
        prices=[
            PriceResponse(
                recommended_price=p.recommended_price,
                confidence=p.confidence,
                floor_price=p.floor_price,
                ceiling_price=p.ceiling_price,
                equilibrium_price=p.equilibrium_price,
            )
            for p in result.prices
        ],
        rankings=[
            RankedListingResponse(
                id=r.id,
                title=r.title,
                score=r.score,
                category=r.category,
            )
            for r in result.rankings
        ],
        evolution_result=evolution_response,
    )
